### PR TITLE
Fixed validation on other keyboard layouts

### PR DESCRIPTION
**Pull request by NeoKms**
Closes issue https://github.com/kommitters/editorjs-undo/issues/167

### CODE REVIEW

**Review by miguelnietoa — DISMISSED** [review]
Hey @NeoKms
Tested and works! Thanks a lot for this useful change in order to support other keyboard layouts.

[undo-keyboard-layout.webm](https://user-images.githubusercontent.com/39246879/201446612-5765c3db-db40-49d5-a013-d536abcc4f3c.webm)



**Note:**
This change is required when the keyboard layout is changed and EditorJS is already instantiated. Otherwise, you can configure your own shortcuts. 👌🏻

**Comment by miguelnietoa** [comment]
Hello @NeoKms 👋🏻 
In order to merge this change we need you to sign the commit. See https://docs.github.com/es/authentication/managing-commit-signature-verification/about-commit-signature-verification

**Comment by NeoKms** [comment]
done

**Review by miguelnietoa — APPROVED** [review]
Thanks for your contribution! ✌🏻

**Pull request merged**
