### PR TITLE
84- Implement the caret feature

### LINKED ISSUE #84: Caret should maintain its current position during CMD+Z and CMD+Y operations within a text block
CMD+Z and CMD+Y operations on text selections within a text block cause the caret to unexpectedly jump to the end of the current text block rather than remaining in its current location.

CMD+Z and CMD+Y operations on text selections within a text block should **not** cause the caret to unexpectedly jump to the end of the current text block. The caret should remain in the position it was in when the CMD+Z or CMD+Y operation was initiated.

If text deleted from within a text block is restored using CMD+Z, the restored text should be highlighted, indicating that it is currently selected.

- If the user then presses the left or right arrow on their keyboard, the caret should be appear at the beginning or end of the restored text, respectively.
- If the user begins entering new characters while a restored selection is highlighted, the restored selection should be replaced and the caret should appear to the right of the first character entered.
- If the user presses CMD+Y to re-delete a restored (and highlighted) selection, the caret should appear immediately to the left of where the first character in the deleted selection was located.

The caret currently jumps to the end of the current text block when CMD+Z and CMD+Y are used, as shown below:

https://user-images.githubusercontent.com/19937217/152803643-5b5024a5-879b-486b-9a58-870ad39e3975.mov

The caret should maintain its position during CMD+Z and CMD+Y operations, as shown below:

https://user-images.githubusercontent.com/19937217/152804766-8ecfd431-d34e-42da-9e18-53fef4f7986c.mov

### PR DESCRIPTION
**Pull request by MarioRodriguezS**
## Description 
Fix #84 
Editorjs-undo did not have a caret functionality, when the undo and redo were pressed the caret is set to the end. 

With the new implementation, the caret is stored, and it is set in the undo and redo actions, also, the tests were updated. 
caret

### CODE REVIEW

**Comment by juanhurtado10** [comment]
@MarioRodriguezS what about the performance with large documents? did you have a chance to test it?

**Comment by MarioRodriguezS** [comment]
> @MarioRodriguezS what about the performance with large documents? did you have a chance to test it?

@juanhurtado10 I just have tested in large documents, and it does not seem to have performance issues. Thanks for the comment.

**Comment by juanhurtado10** [comment]
> @juanhurtado10 I just have tested in large documents, and it does not seem to have performance issues. Thanks for the comment.

Awesome! This will require a new release candidate `v2.0-rc.1`. Could you please update the target branch?

Thanks!

**Comment by MarioRodriguezS** [comment]
> > @juanhurtado10 I just have tested in large documents, and it does not seem to have performance issues. Thanks for the comment.
> 
> Awesome! This will require a new release candidate `v2.0-rc.1`. Could you please update the target branch?
> 
> Thanks!

@juanhurtado10 sure!, target branch updated.

**Review by juanhurtado10 — APPROVED** [review]

**Pull request merged**
