### PR TITLE
Uncaught TypeError: Cannot read properties of undefined (reading 'holder') bug fixed #179

### PR DESCRIPTION
**Pull request by khanakia**

### CODE REVIEW

**Comment by ARH3** [comment]
Hello @miguelnietoa has this been added to the main codebase? I am seeing this same issue when I try to use this plugin.

**Comment by miguelnietoa** [comment]
@ARH3 I was unable not reproduce it... I think it's not an issue. Thank you.

Hey @khanakia, could you describe better how the error occurs? Please!

**Comment by khanakia** [comment]
It's related to editor.js default state and i could find this reference https://github.com/codex-team/editor.js/issues/2084 the same kind of issue was reported by many other users also but i could find this one.

So when you keep undoing and there is nothing to undo then it actually gives the error because undo tries to set the default state it was something like that i cannot remember it completely.

Also, there were many other bugs with undo the undo-redo does not work perfectly with components. So i forked the repo of `editorjs-undo` and customized the code to make it work because our core product is fully dependent of Editor.js so we could not wait to create a pull request and wait it to merge.

**Review by miguelnietoa — APPROVED** [review]
This workaround seems good on our side.

Since these kinds of errors may appear when the plugin is used in conjunction with other components, as you mention... we could not reproduce it properly, but checking some GitHub issues, users say _it looks weird but it works_. 

So thanks for uploading the PR, from our side we do our best to help.
Go ahead and create some PRs if you think the plugin could be improved for the whole community, Thank you! 🤝

**Pull request merged**
